name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pres:
          # - kafka
          # - github_actions
          # - mongodb_change_stream
          # - firestore_rules
          # - qna
          # - aws_lambda
          # - kong_auth
          # - real_time_word_count
          # - feat_eng
          # - stream_adtech
          # - neo4j_recommender
          # - api_genai
          - backend_data_science_ai

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          npm_config_loglevel: verbose
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build_pres -- --name=${{ matrix.pres }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation-${{ matrix.pres }}
          path: dist/

  merge:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge artifacts
        run: |
          mkdir -p dist
          find artifacts -type f -exec cp {} dist/ \;

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: merge
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4